---
# handlers file for docker
- name: Start Docker Service
  listen: start_docker
  service:
     name: docker
     state: started
     enabled: yes
  when: molecule_yml is not defined 

- name: Start Docker Service MOLECULE
  listen: start_docker
  shell: /etc/init.d/docker start
  register: output_docker_service_result
  failed_when: "' * Starting Docker: docker' not in output_docker_service_result.stdout"
  args:
     executable: /usr/bin/bash  
  when: molecule_yml is defined 
